{application,wormhole,
             [{description,"Wormhole captures anything that is emitted out of the callback\n(return value or any kind of exception) and transfers it\nto the calling process in the form {:ok, state} or {:error, reason}.\n"},
              {modules,['Elixir.Wormhole','Elixir.Wormhole.Application',
                        'Elixir.Wormhole.CallbackWrapper',
                        'Elixir.Wormhole.Capture','Elixir.Wormhole.Defaults',
                        'Elixir.Wormhole.Retry']},
              {registered,[]},
              {vsn,"2.2.0"},
              {applications,[kernel,stdlib,elixir,logger]},
              {mod,{'Elixir.Wormhole.Application',[]}}]}.
